// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'chat.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `active_timeline`, `apply_diff`, `block_on_runtime`, `build_client`, `describe_notification_event`, `describe_state`, `map_timeline_item`, `on_runtime`, `persist_session`, `read_stored_session`, `restore_stored_session`, `runtime`, `summarize_room`, `sync_service`, `watch_session_changes`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActiveTimeline`, `ChatConfigInner`, `ClientParams`, `StoredSession`

/// Writes SDK logs to a file (stdout is not visible on iOS/Android).
Future<void> initLogging({required String logFile}) =>
    RustLib.instance.api.crateApiChatInitLogging(logFile: logFile);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChatClient>>
abstract class ChatClient implements RustOpaqueInterface {
  /// Builds the client with encrypted SQLite stores. No network access.
  static Future<ChatClient> create({required ChatConfig config}) =>
      RustLib.instance.api.crateApiChatChatClientCreate(config: config);

  /// Creates (or reuses) an encrypted DM with the given user.
  Future<String> createDm({required String userId});

  /// Enables key backup + secret storage and returns the recovery key
  /// that the user has to write down.
  Future<String> enableRecovery();

  /// Downloads (and decrypts) authenticated media referenced by a timeline item.
  Future<Uint8List> fetchMedia({required String sourceJson});

  /// Completes the OAuth flow with the redirect URL received by the app.
  Future<SessionInfo> finishLogin({required String callbackUrl});

  /// Resolves and decrypts a pushed event (`event_id_only` payload) the way
  /// the Android FCM handler / iOS Notification Service Extension would.
  Future<NotificationContent?> getNotification({
    required String roomId,
    required String eventId,
  });

  Future<void> joinRoom({required String roomId});

  /// Starts an OAuth 2.0 authorization code flow with PKCE against MAS
  /// (dynamic client registration) and returns the URL for the system
  /// browser.
  Future<String> loginUrl();

  Future<void> logout();

  Future<void> markAsRead();

  /// Opens the timeline of a room and streams snapshots of its items.
  /// Opens the timeline of a room; subsequent timeline calls act on it.
  Future<void> openTimeline({required String roomId});

  /// Loads older events; returns true when the start of the room was reached.
  Future<bool> paginateBack({required int count});

  /// Number of token refreshes persisted by this client instance.
  Future<int> persistedRefreshes();

  /// Restores cross-signing and the key backup on a new device.
  Future<void> recover({required String recoveryKey});

  Future<RecoveryStatus> recoveryStatus();

  /// Registers an HTTP pusher (Sygnal) with `event_id_only` payloads.
  Future<void> registerPusher({
    required String pushKey,
    required String appId,
    required String gatewayUrl,
    required String deviceName,
  });

  /// Restores a previously persisted session from the encrypted store.
  Future<SessionInfo?> restoreSession();

  Future<void> sendImage({required String filePath, required String mimeType});

  Future<void> sendText({required String body});

  /// Stops all background work so that another client may open the store.
  Future<void> shutdown();

  /// Starts the sync service (Simplified Sliding Sync + encryption sync).
  Future<void> startSync();

  Future<void> stopSync();

  Future<String?> userId();

  /// `verified` once this device is cross-signed (e.g. after recovery).
  Future<String> verificationState();

  /// Streams the complete room list (joined + invited) as snapshots,
  /// driven by `RoomListService` diffs.
  Stream<List<RoomSummary>> watchRooms();

  /// Streams the sync service state as text (`idle`, `running`, `terminated`, `error`, `offline`).
  Stream<String> watchSyncState();

  /// Streams snapshots of the open timeline.
  Stream<List<TimelineEntry>> watchTimeline();

  /// Authenticated round trip (`/whoami`); refreshes an expired access token.
  Future<String> whoami();
}

class ChatConfig {
  final String homeserverUrl;

  /// Persistent directory for the SQLite stores.
  final String dataDir;

  /// Directory for caches (event cache, media).
  final String cacheDir;

  /// 32 random bytes from the Keychain/Keystore; encrypts all stores.
  final Uint8List storeKey;
  final String clientName;
  final String clientUri;
  final String redirectUri;

  /// Extra trusted root CA (PEM) for local development servers only (not
  /// supported on Android, use the network security config there).
  final String? devRootCertificatePem;

  /// Holder name for the cross-process store/refresh lock. Required on iOS
  /// when a Notification Service Extension shares the store (e.g. `main`).
  final String? crossProcessHolder;

  const ChatConfig({
    required this.homeserverUrl,
    required this.dataDir,
    required this.cacheDir,
    required this.storeKey,
    required this.clientName,
    required this.clientUri,
    required this.redirectUri,
    this.devRootCertificatePem,
    this.crossProcessHolder,
  });

  @override
  int get hashCode =>
      homeserverUrl.hashCode ^
      dataDir.hashCode ^
      cacheDir.hashCode ^
      storeKey.hashCode ^
      clientName.hashCode ^
      clientUri.hashCode ^
      redirectUri.hashCode ^
      devRootCertificatePem.hashCode ^
      crossProcessHolder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatConfig &&
          runtimeType == other.runtimeType &&
          homeserverUrl == other.homeserverUrl &&
          dataDir == other.dataDir &&
          cacheDir == other.cacheDir &&
          storeKey == other.storeKey &&
          clientName == other.clientName &&
          clientUri == other.clientUri &&
          redirectUri == other.redirectUri &&
          devRootCertificatePem == other.devRootCertificatePem &&
          crossProcessHolder == other.crossProcessHolder;
}

@freezed
sealed class MessageKind with _$MessageKind {
  const MessageKind._();

  const factory MessageKind.text({required String body}) = MessageKind_Text;
  const factory MessageKind.image({
    required String body,
    required String sourceJson,
    int? width,
    int? height,
  }) = MessageKind_Image;
  const factory MessageKind.unableToDecrypt() = MessageKind_UnableToDecrypt;
  const factory MessageKind.redacted() = MessageKind_Redacted;
  const factory MessageKind.other({required String description}) =
      MessageKind_Other;
}

class NotificationContent {
  final String roomName;
  final String? senderName;
  final String body;
  final bool isDirect;
  final bool? isEncrypted;

  const NotificationContent({
    required this.roomName,
    this.senderName,
    required this.body,
    required this.isDirect,
    this.isEncrypted,
  });

  @override
  int get hashCode =>
      roomName.hashCode ^
      senderName.hashCode ^
      body.hashCode ^
      isDirect.hashCode ^
      isEncrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationContent &&
          runtimeType == other.runtimeType &&
          roomName == other.roomName &&
          senderName == other.senderName &&
          body == other.body &&
          isDirect == other.isDirect &&
          isEncrypted == other.isEncrypted;
}

enum RecoveryStatus { unknown, enabled, disabled, incomplete }

class RoomSummary {
  final String roomId;
  final String displayName;
  final bool isEncrypted;
  final bool isDirect;
  final bool isInvite;
  final BigInt unreadCount;
  final PlatformInt64? latestTimestampMs;

  const RoomSummary({
    required this.roomId,
    required this.displayName,
    required this.isEncrypted,
    required this.isDirect,
    required this.isInvite,
    required this.unreadCount,
    this.latestTimestampMs,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      displayName.hashCode ^
      isEncrypted.hashCode ^
      isDirect.hashCode ^
      isInvite.hashCode ^
      unreadCount.hashCode ^
      latestTimestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          displayName == other.displayName &&
          isEncrypted == other.isEncrypted &&
          isDirect == other.isDirect &&
          isInvite == other.isInvite &&
          unreadCount == other.unreadCount &&
          latestTimestampMs == other.latestTimestampMs;
}

class SessionInfo {
  final String userId;
  final String deviceId;

  const SessionInfo({required this.userId, required this.deviceId});

  @override
  int get hashCode => userId.hashCode ^ deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionInfo &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          deviceId == other.deviceId;
}

@freezed
sealed class TimelineEntry with _$TimelineEntry {
  const TimelineEntry._();

  const factory TimelineEntry.message({
    required String uniqueId,
    String? eventId,
    required String senderId,
    String? senderName,
    required PlatformInt64 timestampMs,
    required bool isOwn,
    required bool isSending,
    required bool isFailed,
    required MessageKind kind,
  }) = TimelineEntry_Message;
  const factory TimelineEntry.state({
    required String uniqueId,
    required String description,
  }) = TimelineEntry_State;
  const factory TimelineEntry.dayDivider({
    required String uniqueId,
    required PlatformInt64 timestampMs,
  }) = TimelineEntry_DayDivider;
  const factory TimelineEntry.readMarker({required String uniqueId}) =
      TimelineEntry_ReadMarker;
  const factory TimelineEntry.timelineStart({required String uniqueId}) =
      TimelineEntry_TimelineStart;
}
