// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'encryption.dart';
import 'error.dart';
import 'notifications.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rooms.dart';
import 'timeline.dart';

// These functions are ignored because they are not marked as `pub`: `sync_service`, `watch_session_changes`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChatConfigInner`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChatClient>>
abstract class ChatClient implements RustOpaqueInterface {
  /// Builds the client with encrypted SQLite stores. No network access.
  static Future<ChatClient> create({required ChatConfig config}) =>
      RustLib.instance.api.crateApiClientChatClientCreate(config: config);

  /// Creates (or reuses) an encrypted DM with the given user.
  Future<String> createDm({required String userId});

  /// Enables key backup + secret storage and returns the recovery key
  /// that the user has to write down.
  Future<String> enableRecovery();

  /// Downloads (and decrypts) media referenced by a timeline item
  /// (`EventContent::*::media`). Uses the SDK media cache.
  Future<Uint8List> fetchMedia({required String media});

  /// Completes the OAuth flow with the redirect URL received by the app.
  Future<SessionInfo> finishLogin({required String callbackUrl});

  /// Resolves and decrypts a pushed event (`event_id_only` payload) the way
  /// the Android FCM handler / iOS Notification Service Extension would.
  Future<NotificationContent?> getNotification({
    required String roomId,
    required String eventId,
  });

  Future<void> joinRoom({required String roomId});

  /// Extends the visible room list by one page.
  Future<void> loadMoreRooms();

  /// Starts an OAuth 2.0 authorization code flow with PKCE against MAS
  /// (dynamic client registration) and returns the URL for the system
  /// browser.
  Future<String> loginUrl();

  Future<void> logout();

  /// Number of token refreshes persisted by this client instance.
  Future<int> persistedRefreshes();

  /// Restores cross-signing and the key backup on a new device.
  Future<void> recover({required String recoveryKey});

  Future<RecoveryStatus> recoveryStatus();

  /// Registers an HTTP pusher (Sygnal) with `event_id_only` payloads.
  Future<void> registerPusher({
    required String pushKey,
    required String appId,
    required String gatewayUrl,
    required String deviceName,
  });

  /// Restores a previously persisted session from the encrypted store.
  Future<SessionInfo?> restoreSession();

  Future<void> setRoomFilter({required RoomFilter filter});

  /// Stops all background work so that another client may open the store.
  Future<void> shutdown();

  /// Starts the sync service (Simplified Sliding Sync + encryption sync).
  Future<void> startSync();

  Future<void> stopSync();

  /// Opens the live timeline of a room.
  Future<ChatTimeline> timeline({required String roomId});

  Future<String?> userId();

  /// `verified` once this device is cross-signed (e.g. after recovery).
  Future<String> verificationState();

  /// Streams the room list as diffs. The first batch resets the list.
  /// Starting a new watch replaces the previous one.
  Stream<List<RoomListDiff>> watchRoomList();

  /// Streams the sync service state as text (`idle`, `running`, `terminated`, `error`, `offline`).
  Stream<String> watchSyncState();

  /// Authenticated round trip (`/whoami`); refreshes an expired access token.
  Future<String> whoami();
}

class ChatConfig {
  final String homeserverUrl;

  /// Persistent directory for the SQLite stores.
  final String dataDir;

  /// Directory for caches (event cache, media).
  final String cacheDir;

  /// 32 random bytes from the Keychain/Keystore; encrypts all stores.
  final Uint8List storeKey;
  final String clientName;
  final String clientUri;
  final String redirectUri;

  /// Extra trusted root CA (PEM) for local development servers only (not
  /// supported on Android; install a user CA there).
  final String? devRootCertificatePem;

  /// Holder name for the cross-process store/refresh lock. Required on iOS
  /// when a Notification Service Extension shares the store (e.g. `main`).
  final String? crossProcessHolder;

  const ChatConfig({
    required this.homeserverUrl,
    required this.dataDir,
    required this.cacheDir,
    required this.storeKey,
    required this.clientName,
    required this.clientUri,
    required this.redirectUri,
    this.devRootCertificatePem,
    this.crossProcessHolder,
  });

  @override
  int get hashCode =>
      homeserverUrl.hashCode ^
      dataDir.hashCode ^
      cacheDir.hashCode ^
      storeKey.hashCode ^
      clientName.hashCode ^
      clientUri.hashCode ^
      redirectUri.hashCode ^
      devRootCertificatePem.hashCode ^
      crossProcessHolder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatConfig &&
          runtimeType == other.runtimeType &&
          homeserverUrl == other.homeserverUrl &&
          dataDir == other.dataDir &&
          cacheDir == other.cacheDir &&
          storeKey == other.storeKey &&
          clientName == other.clientName &&
          clientUri == other.clientUri &&
          redirectUri == other.redirectUri &&
          devRootCertificatePem == other.devRootCertificatePem &&
          crossProcessHolder == other.crossProcessHolder;
}

class SessionInfo {
  final String userId;
  final String deviceId;

  const SessionInfo({required this.userId, required this.deviceId});

  @override
  int get hashCode => userId.hashCode ^ deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionInfo &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          deviceId == other.deviceId;
}
