// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `classify_http`, `classify_kind`, `classify_oauth`, `classify_refresh`, `classify_sdk`, `clone_kind`, `invalid`, `retry_after_ms`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`

@freezed
sealed class ChatError with _$ChatError implements FrbException {
  const ChatError._();

  /// No connection to the homeserver or MAS (retry later).
  const factory ChatError.network() = ChatError_Network;

  /// The session is no longer valid; the user must sign in again.
  const factory ChatError.sessionExpired() = ChatError_SessionExpired;

  /// The account was locked (e.g. chat access revoked in NGO.Tools).
  const factory ChatError.accountLocked() = ChatError_AccountLocked;
  const factory ChatError.forbidden() = ChatError_Forbidden;
  const factory ChatError.notFound() = ChatError_NotFound;
  const factory ChatError.rateLimited({BigInt? retryAfterMs}) =
      ChatError_RateLimited;
  const factory ChatError.crypto({required String message}) = ChatError_Crypto;
  const factory ChatError.storage({required String message}) =
      ChatError_Storage;
  const factory ChatError.invalidInput({required String message}) =
      ChatError_InvalidInput;
  const factory ChatError.internal({required String message}) =
      ChatError_Internal;
}
