// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `describe_notification_event`

class NotificationContent {
  final String roomName;
  final String? senderName;
  final String body;
  final bool isDirect;
  final bool? isEncrypted;

  const NotificationContent({
    required this.roomName,
    this.senderName,
    required this.body,
    required this.isDirect,
    this.isEncrypted,
  });

  @override
  int get hashCode =>
      roomName.hashCode ^
      senderName.hashCode ^
      body.hashCode ^
      isDirect.hashCode ^
      isEncrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationContent &&
          runtimeType == other.runtimeType &&
          roomName == other.roomName &&
          senderName == other.senderName &&
          body == other.body &&
          isDirect == other.isDirect &&
          isEncrypted == other.isEncrypted;
}
