// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `summarize_room`

class RoomSummary {
  final String roomId;
  final String displayName;
  final bool isEncrypted;
  final bool isDirect;
  final bool isInvite;
  final BigInt unreadCount;
  final PlatformInt64? latestTimestampMs;

  const RoomSummary({
    required this.roomId,
    required this.displayName,
    required this.isEncrypted,
    required this.isDirect,
    required this.isInvite,
    required this.unreadCount,
    this.latestTimestampMs,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      displayName.hashCode ^
      isEncrypted.hashCode ^
      isDirect.hashCode ^
      isInvite.hashCode ^
      unreadCount.hashCode ^
      latestTimestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          displayName == other.displayName &&
          isEncrypted == other.isEncrypted &&
          isDirect == other.isDirect &&
          isInvite == other.isInvite &&
          unreadCount == other.unreadCount &&
          latestTimestampMs == other.latestTimestampMs;
}
