// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'room.dart';
import 'timeline.dart';
part 'rooms.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `display_name`, `filter_for`, `latest_event`, `map_diff`, `not_left`, `refilter_room_lists`, `refresh_notification_mode`, `send_room_command`, `stop_room_lists`, `summarize_all`, `summarize`, `to_u32`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RoomListCommand`, `RoomListWatch`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

class LatestEvent {
  final String senderId;
  final String? senderName;
  final bool isOwn;
  final PlatformInt64 timestampMs;
  final MessagePreview preview;

  /// A local echo that is still being sent or failed to send.
  final bool isUnsent;

  const LatestEvent({
    required this.senderId,
    this.senderName,
    required this.isOwn,
    required this.timestampMs,
    required this.preview,
    required this.isUnsent,
  });

  @override
  int get hashCode =>
      senderId.hashCode ^
      senderName.hashCode ^
      isOwn.hashCode ^
      timestampMs.hashCode ^
      preview.hashCode ^
      isUnsent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LatestEvent &&
          runtimeType == other.runtimeType &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          isOwn == other.isOwn &&
          timestampMs == other.timestampMs &&
          preview == other.preview &&
          isUnsent == other.isUnsent;
}

enum Membership { joined, invited }

enum RoomFilter {
  /// Joined rooms and invites.
  all,

  /// Direct messages.
  people,

  /// Group and event rooms.
  groups,
  invites,

  /// Rooms with unread messages.
  unread,
}

enum RoomKind { direct, group }

@freezed
sealed class RoomListDiff with _$RoomListDiff {
  const RoomListDiff._();

  const factory RoomListDiff.append({required List<RoomSummary> values}) =
      RoomListDiff_Append;
  const factory RoomListDiff.clear() = RoomListDiff_Clear;
  const factory RoomListDiff.pushFront({required RoomSummary value}) =
      RoomListDiff_PushFront;
  const factory RoomListDiff.pushBack({required RoomSummary value}) =
      RoomListDiff_PushBack;
  const factory RoomListDiff.popFront() = RoomListDiff_PopFront;
  const factory RoomListDiff.popBack() = RoomListDiff_PopBack;
  const factory RoomListDiff.insert({
    required int index,
    required RoomSummary value,
  }) = RoomListDiff_Insert;
  const factory RoomListDiff.set_({
    required int index,
    required RoomSummary value,
  }) = RoomListDiff_Set;
  const factory RoomListDiff.remove({required int index}) = RoomListDiff_Remove;
  const factory RoomListDiff.truncate({required int length}) =
      RoomListDiff_Truncate;
  const factory RoomListDiff.reset({required List<RoomSummary> values}) =
      RoomListDiff_Reset;
}

class RoomSummary {
  final String id;
  final String name;

  /// `mxc://` URI of the room avatar (fetch via the media API).
  final String? avatarUrl;
  final RoomKind kind;
  final Membership membership;
  final bool isEncrypted;
  final int unreadMessages;
  final int unreadMentions;
  final LatestEvent? latest;

  /// Mode set by the user for this room; `None` follows the default.
  final NotificationMode? notificationMode;

  const RoomSummary({
    required this.id,
    required this.name,
    this.avatarUrl,
    required this.kind,
    required this.membership,
    required this.isEncrypted,
    required this.unreadMessages,
    required this.unreadMentions,
    this.latest,
    this.notificationMode,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      avatarUrl.hashCode ^
      kind.hashCode ^
      membership.hashCode ^
      isEncrypted.hashCode ^
      unreadMessages.hashCode ^
      unreadMentions.hashCode ^
      latest.hashCode ^
      notificationMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          kind == other.kind &&
          membership == other.membership &&
          isEncrypted == other.isEncrypted &&
          unreadMessages == other.unreadMessages &&
          unreadMentions == other.unreadMentions &&
          latest == other.latest &&
          notificationMode == other.notificationMode;
}
