// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_sdk`, `member_role`, `room`, `shared_settings`, `to_sdk`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

class Member {
  final String userId;
  final String? displayName;

  /// `mxc://` URI of the avatar (fetch via the media API).
  final String? avatarUrl;
  final MemberState state;
  final MemberRole role;
  final bool isOwn;

  const Member({
    required this.userId,
    this.displayName,
    this.avatarUrl,
    required this.state,
    required this.role,
    required this.isOwn,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      avatarUrl.hashCode ^
      state.hashCode ^
      role.hashCode ^
      isOwn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Member &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl &&
          state == other.state &&
          role == other.role &&
          isOwn == other.isOwn;
}

enum MemberRole { admin, moderator, user }

enum MemberState { joined, invited }

enum NotificationMode { allMessages, mentionsOnly, mute }

class RoomNotificationSettings {
  final NotificationMode mode;

  /// True when the room follows the account default for its kind.
  final bool isDefault;

  const RoomNotificationSettings({required this.mode, required this.isDefault});

  @override
  int get hashCode => mode.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomNotificationSettings &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          isDefault == other.isDefault;
}
