// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'timeline.dart';
part 'threads.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `map_diff`, `thread_event`, `thread_info`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChatThreadList>>
abstract class ChatThreadList implements RustOpaqueInterface {
  /// Stops streaming.
  Future<void> close();

  /// Loads the next page of threads; returns true when all are loaded.
  Future<bool> paginate();

  /// Streams the thread list as diffs; the first batch resets the list.
  Stream<List<ThreadListDiff>> watch();
}

class ThreadEvent {
  final String eventId;
  final Sender sender;
  final PlatformInt64 timestampMs;
  final bool isOwn;

  /// `None` while the content is not known (e.g. not yet decrypted).
  final MessagePreview? preview;

  const ThreadEvent({
    required this.eventId,
    required this.sender,
    required this.timestampMs,
    required this.isOwn,
    this.preview,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      sender.hashCode ^
      timestampMs.hashCode ^
      isOwn.hashCode ^
      preview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          sender == other.sender &&
          timestampMs == other.timestampMs &&
          isOwn == other.isOwn &&
          preview == other.preview;
}

class ThreadInfo {
  final ThreadEvent root;
  final ThreadEvent? latest;
  final int replyCount;

  const ThreadInfo({required this.root, this.latest, required this.replyCount});

  @override
  int get hashCode => root.hashCode ^ latest.hashCode ^ replyCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadInfo &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          latest == other.latest &&
          replyCount == other.replyCount;
}

@freezed
sealed class ThreadListDiff with _$ThreadListDiff {
  const ThreadListDiff._();

  const factory ThreadListDiff.append({required List<ThreadInfo> values}) =
      ThreadListDiff_Append;
  const factory ThreadListDiff.clear() = ThreadListDiff_Clear;
  const factory ThreadListDiff.pushFront({required ThreadInfo value}) =
      ThreadListDiff_PushFront;
  const factory ThreadListDiff.pushBack({required ThreadInfo value}) =
      ThreadListDiff_PushBack;
  const factory ThreadListDiff.popFront() = ThreadListDiff_PopFront;
  const factory ThreadListDiff.popBack() = ThreadListDiff_PopBack;
  const factory ThreadListDiff.insert({
    required int index,
    required ThreadInfo value,
  }) = ThreadListDiff_Insert;
  const factory ThreadListDiff.set_({
    required int index,
    required ThreadInfo value,
  }) = ThreadListDiff_Set;
  const factory ThreadListDiff.remove({required int index}) =
      ThreadListDiff_Remove;
  const factory ThreadListDiff.truncate({required int length}) =
      ThreadListDiff_Truncate;
  const factory ThreadListDiff.reset({required List<ThreadInfo> values}) =
      ThreadListDiff_Reset;
}
