// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'timeline.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `decryption_failure`, `event_content`, `item_id`, `map_diff`, `map_event`, `map_item`, `media_ref`, `message_preview`, `parse_event_id`, `reactions`, `ready`, `reply_preview`, `send_handle`, `sender`, `thumbnail`, `to_u32`, `to_u64`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `drop`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChatTimeline>>
abstract class ChatTimeline implements RustOpaqueInterface {
  /// Cancels a pending or failed local echo; returns false if it was
  /// already sent.
  Future<bool> cancel({required EventKey key});

  /// Stops streaming; the timeline can be watched again later.
  Future<void> close();

  /// Replaces the text of an own message.
  Future<void> edit({required EventKey key, required String body});

  /// Loads the replied-to event of `event_id` so that its `reply_to`
  /// preview gets sender and content (arrives as a diff).
  Future<void> loadReplyDetails({required String eventId});

  /// Moves the read receipt to the latest event.
  Future<void> markRead();

  /// Loads older events; returns true when the start of the room was reached.
  Future<bool> paginateBack({required int count});

  /// Deletes a message (own messages, or others' with moderation rights).
  Future<void> redact({required EventKey key, String? reason});

  /// Retries a local echo whose sending failed.
  Future<void> retry({required EventKey key});

  /// Sends an image. Upload progress appears on the local echo
  /// (`SendState::Sending`). Pass a small `thumbnail` for encrypted rooms:
  /// the server cannot scale encrypted media.
  Future<void> sendImage({required ImageAttachment image});

  /// Sends a plain-text message, optionally as a reply to `reply_to`.
  Future<void> sendText({required String body, String? replyTo});

  /// Tells the others whether the user is typing (the SDK throttles
  /// repeated notices and lets them expire).
  Future<void> setTyping({required bool typing});

  /// Adds or removes an own reaction; returns true if it is now set.
  Future<bool> toggleReaction({
    required EventKey key,
    required String reaction,
  });

  /// Streams the timeline as diffs; the first batch resets the list.
  /// Starting a new watch replaces the previous one.
  Stream<List<TimelineDiff>> watch();

  /// Streams the other members currently typing in this room.
  Stream<List<Sender>> watchTyping();
}

/// Why a message cannot be decrypted (yet), as far as this device can tell.
enum DecryptionFailure {
  /// No explanation; the keys may still arrive (e.g. from the key backup).
  unknown,

  /// Sent before this account joined the room.
  sentBeforeJoined,

  /// Sent before this device existed and there is no key backup to restore
  /// the keys from.
  historicalNoBackup,

  /// Sent before this device existed; the key backup is available after
  /// entering the recovery key.
  historicalUnverifiedDevice,

  /// The sender did not share the keys with this device (e.g. because it
  /// is not verified).
  withheld,

  /// The sending device or identity is not trusted.
  untrustedSender,
}

@freezed
sealed class EventContent with _$EventContent {
  const EventContent._();

  const factory EventContent.text({required String body}) = EventContent_Text;
  const factory EventContent.image({
    String? caption,
    required String filename,

    /// Opaque media reference for the media API.
    required String media,

    /// Small preview uploaded by the sender (always set for encrypted
    /// images sent by this app; fetch it with `fetch_media`).
    String? thumbnail,
    int? width,
    int? height,
    String? blurhash,
  }) = EventContent_Image;
  const factory EventContent.video({
    String? caption,
    required String filename,
    required String media,
  }) = EventContent_Video;
  const factory EventContent.audio({
    required String filename,
    required String media,
  }) = EventContent_Audio;
  const factory EventContent.file({
    String? caption,
    required String filename,
    required String media,
    BigInt? size,
  }) = EventContent_File;
  const factory EventContent.redacted() = EventContent_Redacted;
  const factory EventContent.unableToDecrypt({
    required DecryptionFailure reason,
  }) = EventContent_UnableToDecrypt;
  const factory EventContent.membership({
    required String userId,
    required MembershipKind change,
  }) = EventContent_Membership;
  const factory EventContent.profileChange({required String userId}) =
      EventContent_ProfileChange;
  const factory EventContent.roomState({required String eventType}) =
      EventContent_RoomState;
  const factory EventContent.unsupported() = EventContent_Unsupported;
}

class EventItem {
  final EventKey key;
  final String? eventId;
  final Sender sender;
  final PlatformInt64 timestampMs;
  final bool isOwn;
  final bool canEdit;
  final bool canReply;
  final SendState sendState;
  final EventContent content;
  final ReplyPreview? replyTo;
  final List<Reaction> reactions;
  final bool isEdited;

  /// Set when this event belongs to a thread (event id of the root).
  final String? threadRoot;

  /// Set on a thread root: number of replies and the latest reply.
  final ThreadSummary? thread;

  const EventItem({
    required this.key,
    this.eventId,
    required this.sender,
    required this.timestampMs,
    required this.isOwn,
    required this.canEdit,
    required this.canReply,
    required this.sendState,
    required this.content,
    this.replyTo,
    required this.reactions,
    required this.isEdited,
    this.threadRoot,
    this.thread,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      eventId.hashCode ^
      sender.hashCode ^
      timestampMs.hashCode ^
      isOwn.hashCode ^
      canEdit.hashCode ^
      canReply.hashCode ^
      sendState.hashCode ^
      content.hashCode ^
      replyTo.hashCode ^
      reactions.hashCode ^
      isEdited.hashCode ^
      threadRoot.hashCode ^
      thread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventItem &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          eventId == other.eventId &&
          sender == other.sender &&
          timestampMs == other.timestampMs &&
          isOwn == other.isOwn &&
          canEdit == other.canEdit &&
          canReply == other.canReply &&
          sendState == other.sendState &&
          content == other.content &&
          replyTo == other.replyTo &&
          reactions == other.reactions &&
          isEdited == other.isEdited &&
          threadRoot == other.threadRoot &&
          thread == other.thread;
}

@freezed
sealed class EventKey with _$EventKey {
  const EventKey._();

  const factory EventKey.local({required String transactionId}) =
      EventKey_Local;
  const factory EventKey.remote({required String eventId}) = EventKey_Remote;
}

/// An image to send; `width`/`height` are the pixel size of the file.
class ImageAttachment {
  final String filePath;
  final String mimeType;
  final String? caption;
  final int? width;
  final int? height;
  final String? blurhash;
  final ImageThumbnail? thumbnail;

  const ImageAttachment({
    required this.filePath,
    required this.mimeType,
    this.caption,
    this.width,
    this.height,
    this.blurhash,
    this.thumbnail,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^
      mimeType.hashCode ^
      caption.hashCode ^
      width.hashCode ^
      height.hashCode ^
      blurhash.hashCode ^
      thumbnail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageAttachment &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          mimeType == other.mimeType &&
          caption == other.caption &&
          width == other.width &&
          height == other.height &&
          blurhash == other.blurhash &&
          thumbnail == other.thumbnail;
}

/// Encoded preview image (e.g. JPEG, longest side ~800 px).
class ImageThumbnail {
  final Uint8List data;
  final String mimeType;
  final int width;
  final int height;

  const ImageThumbnail({
    required this.data,
    required this.mimeType,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      data.hashCode ^ mimeType.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageThumbnail &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          mimeType == other.mimeType &&
          width == other.width &&
          height == other.height;
}

enum MembershipKind {
  joined,
  left,
  invited,
  invitationAccepted,
  invitationRejected,
  kicked,
  banned,
  other,
}

@freezed
sealed class MessagePreview with _$MessagePreview {
  const MessagePreview._();

  const factory MessagePreview.text({required String body}) =
      MessagePreview_Text;
  const factory MessagePreview.image() = MessagePreview_Image;
  const factory MessagePreview.video() = MessagePreview_Video;
  const factory MessagePreview.audio() = MessagePreview_Audio;
  const factory MessagePreview.file() = MessagePreview_File;
  const factory MessagePreview.location() = MessagePreview_Location;
  const factory MessagePreview.poll() = MessagePreview_Poll;
  const factory MessagePreview.sticker() = MessagePreview_Sticker;
  const factory MessagePreview.redacted() = MessagePreview_Redacted;
  const factory MessagePreview.unableToDecrypt() =
      MessagePreview_UnableToDecrypt;

  /// State changes and anything the app does not render as a message.
  const factory MessagePreview.other() = MessagePreview_Other;
}

class Reaction {
  final String key;
  final int count;
  final bool byMe;

  const Reaction({required this.key, required this.count, required this.byMe});

  @override
  int get hashCode => key.hashCode ^ count.hashCode ^ byMe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Reaction &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          count == other.count &&
          byMe == other.byMe;
}

class ReplyPreview {
  final String eventId;

  /// `None` until the replied-to event is loaded (see `load_reply_details`).
  final Sender? sender;
  final MessagePreview? preview;

  const ReplyPreview({required this.eventId, this.sender, this.preview});

  @override
  int get hashCode => eventId.hashCode ^ sender.hashCode ^ preview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReplyPreview &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          sender == other.sender &&
          preview == other.preview;
}

@freezed
sealed class SendState with _$SendState {
  const SendState._();

  /// Queued or uploading; `progress` is set while media is uploaded.
  const factory SendState.sending({UploadProgress? progress}) =
      SendState_Sending;
  const factory SendState.sent() = SendState_Sent;
  const factory SendState.failed({required bool recoverable}) =
      SendState_Failed;
}

class Sender {
  final String id;
  final String? name;

  /// `mxc://` URI of the avatar.
  final String? avatarUrl;

  const Sender({required this.id, this.name, this.avatarUrl});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Sender &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl;
}

class ThreadSummary {
  final int replyCount;
  final Sender? latestSender;
  final MessagePreview? latestPreview;

  const ThreadSummary({
    required this.replyCount,
    this.latestSender,
    this.latestPreview,
  });

  @override
  int get hashCode =>
      replyCount.hashCode ^ latestSender.hashCode ^ latestPreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadSummary &&
          runtimeType == other.runtimeType &&
          replyCount == other.replyCount &&
          latestSender == other.latestSender &&
          latestPreview == other.latestPreview;
}

@freezed
sealed class TimelineDiff with _$TimelineDiff {
  const TimelineDiff._();

  const factory TimelineDiff.append({required List<TimelineItem> values}) =
      TimelineDiff_Append;
  const factory TimelineDiff.clear() = TimelineDiff_Clear;
  const factory TimelineDiff.pushFront({required TimelineItem value}) =
      TimelineDiff_PushFront;
  const factory TimelineDiff.pushBack({required TimelineItem value}) =
      TimelineDiff_PushBack;
  const factory TimelineDiff.popFront() = TimelineDiff_PopFront;
  const factory TimelineDiff.popBack() = TimelineDiff_PopBack;
  const factory TimelineDiff.insert({
    required int index,
    required TimelineItem value,
  }) = TimelineDiff_Insert;
  const factory TimelineDiff.set_({
    required int index,
    required TimelineItem value,
  }) = TimelineDiff_Set;
  const factory TimelineDiff.remove({required int index}) = TimelineDiff_Remove;
  const factory TimelineDiff.truncate({required int length}) =
      TimelineDiff_Truncate;
  const factory TimelineDiff.reset({required List<TimelineItem> values}) =
      TimelineDiff_Reset;
}

class TimelineItem {
  /// Stable id of the item across diffs.
  final String id;
  final TimelineItemKind kind;

  const TimelineItem({required this.id, required this.kind});

  @override
  int get hashCode => id.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind;
}

@freezed
sealed class TimelineItemKind with _$TimelineItemKind {
  const TimelineItemKind._();

  const factory TimelineItemKind.event({required EventItem event}) =
      TimelineItemKind_Event;
  const factory TimelineItemKind.dateDivider({
    required PlatformInt64 timestampMs,
  }) = TimelineItemKind_DateDivider;
  const factory TimelineItemKind.readMarker() = TimelineItemKind_ReadMarker;
  const factory TimelineItemKind.timelineStart() =
      TimelineItemKind_TimelineStart;
}

/// Uploaded bytes of a media message (file and thumbnail combined).
class UploadProgress {
  final BigInt currentBytes;
  final BigInt totalBytes;

  const UploadProgress({required this.currentBytes, required this.totalBytes});

  @override
  int get hashCode => currentBytes.hashCode ^ totalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadProgress &&
          runtimeType == other.runtimeType &&
          currentBytes == other.currentBytes &&
          totalBytes == other.totalBytes;
}
