// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'timeline.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `active_timeline`, `apply_diff`, `describe_state`, `map_timeline_item`, `message_preview`

@freezed
sealed class MessageKind with _$MessageKind {
  const MessageKind._();

  const factory MessageKind.text({required String body}) = MessageKind_Text;
  const factory MessageKind.image({
    required String body,
    required String sourceJson,
    int? width,
    int? height,
  }) = MessageKind_Image;
  const factory MessageKind.unableToDecrypt() = MessageKind_UnableToDecrypt;
  const factory MessageKind.redacted() = MessageKind_Redacted;
  const factory MessageKind.other({required String description}) =
      MessageKind_Other;
}

@freezed
sealed class MessagePreview with _$MessagePreview {
  const MessagePreview._();

  const factory MessagePreview.text({required String body}) =
      MessagePreview_Text;
  const factory MessagePreview.image() = MessagePreview_Image;
  const factory MessagePreview.video() = MessagePreview_Video;
  const factory MessagePreview.audio() = MessagePreview_Audio;
  const factory MessagePreview.file() = MessagePreview_File;
  const factory MessagePreview.location() = MessagePreview_Location;
  const factory MessagePreview.poll() = MessagePreview_Poll;
  const factory MessagePreview.sticker() = MessagePreview_Sticker;
  const factory MessagePreview.redacted() = MessagePreview_Redacted;
  const factory MessagePreview.unableToDecrypt() =
      MessagePreview_UnableToDecrypt;

  /// State changes and anything the app does not render as a message.
  const factory MessagePreview.other() = MessagePreview_Other;
}

@freezed
sealed class TimelineEntry with _$TimelineEntry {
  const TimelineEntry._();

  const factory TimelineEntry.message({
    required String uniqueId,
    String? eventId,
    required String senderId,
    String? senderName,
    required PlatformInt64 timestampMs,
    required bool isOwn,
    required bool isSending,
    required bool isFailed,
    required MessageKind kind,
  }) = TimelineEntry_Message;
  const factory TimelineEntry.state({
    required String uniqueId,
    required String description,
  }) = TimelineEntry_State;
  const factory TimelineEntry.dayDivider({
    required String uniqueId,
    required PlatformInt64 timestampMs,
  }) = TimelineEntry_DayDivider;
  const factory TimelineEntry.readMarker({required String uniqueId}) =
      TimelineEntry_ReadMarker;
  const factory TimelineEntry.timelineStart({required String uniqueId}) =
      TimelineEntry_TimelineStart;
}
