// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/chat.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiChatInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 201347134;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ngotools_matrix_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ChatClient> crateApiChatChatClientCreate({required ChatConfig config});

  Future<String> crateApiChatChatClientCreateDm({
    required ChatClient that,
    required String userId,
  });

  Future<String> crateApiChatChatClientEnableRecovery({
    required ChatClient that,
  });

  Future<Uint8List> crateApiChatChatClientFetchMedia({
    required ChatClient that,
    required String sourceJson,
  });

  Future<SessionInfo> crateApiChatChatClientFinishLogin({
    required ChatClient that,
    required String callbackUrl,
  });

  Future<NotificationContent?> crateApiChatChatClientGetNotification({
    required ChatClient that,
    required String roomId,
    required String eventId,
  });

  Future<void> crateApiChatChatClientJoinRoom({
    required ChatClient that,
    required String roomId,
  });

  Future<String> crateApiChatChatClientLoginUrl({required ChatClient that});

  Future<void> crateApiChatChatClientLogout({required ChatClient that});

  Future<void> crateApiChatChatClientMarkAsRead({required ChatClient that});

  Future<void> crateApiChatChatClientOpenTimeline({
    required ChatClient that,
    required String roomId,
  });

  Future<bool> crateApiChatChatClientPaginateBack({
    required ChatClient that,
    required int count,
  });

  Future<int> crateApiChatChatClientPersistedRefreshes({
    required ChatClient that,
  });

  Future<void> crateApiChatChatClientRecover({
    required ChatClient that,
    required String recoveryKey,
  });

  Future<RecoveryStatus> crateApiChatChatClientRecoveryStatus({
    required ChatClient that,
  });

  Future<void> crateApiChatChatClientRegisterPusher({
    required ChatClient that,
    required String pushKey,
    required String appId,
    required String gatewayUrl,
    required String deviceName,
  });

  Future<SessionInfo?> crateApiChatChatClientRestoreSession({
    required ChatClient that,
  });

  Future<void> crateApiChatChatClientSendImage({
    required ChatClient that,
    required String filePath,
    required String mimeType,
  });

  Future<void> crateApiChatChatClientSendText({
    required ChatClient that,
    required String body,
  });

  Future<void> crateApiChatChatClientShutdown({required ChatClient that});

  Future<void> crateApiChatChatClientStartSync({required ChatClient that});

  Future<void> crateApiChatChatClientStopSync({required ChatClient that});

  Future<String?> crateApiChatChatClientUserId({required ChatClient that});

  Future<String> crateApiChatChatClientVerificationState({
    required ChatClient that,
  });

  Stream<List<RoomSummary>> crateApiChatChatClientWatchRooms({
    required ChatClient that,
  });

  Stream<String> crateApiChatChatClientWatchSyncState({
    required ChatClient that,
  });

  Stream<List<TimelineEntry>> crateApiChatChatClientWatchTimeline({
    required ChatClient that,
  });

  Future<String> crateApiChatChatClientWhoami({required ChatClient that});

  Future<void> crateApiChatInitApp();

  Future<void> crateApiChatInitLogging({required String logFile});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ChatClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ChatClient;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ChatClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ChatClient> crateApiChatChatClientCreate({
    required ChatConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_chat_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientCreateConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientCreateConstMeta =>
      const TaskConstMeta(debugName: "ChatClient_create", argNames: ["config"]);

  @override
  Future<String> crateApiChatChatClientCreateDm({
    required ChatClient that,
    required String userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientCreateDmConstMeta,
        argValues: [that, userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientCreateDmConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_create_dm",
        argNames: ["that", "userId"],
      );

  @override
  Future<String> crateApiChatChatClientEnableRecovery({
    required ChatClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientEnableRecoveryConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientEnableRecoveryConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_enable_recovery",
        argNames: ["that"],
      );

  @override
  Future<Uint8List> crateApiChatChatClientFetchMedia({
    required ChatClient that,
    required String sourceJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_String(sourceJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientFetchMediaConstMeta,
        argValues: [that, sourceJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientFetchMediaConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_fetch_media",
        argNames: ["that", "sourceJson"],
      );

  @override
  Future<SessionInfo> crateApiChatChatClientFinishLogin({
    required ChatClient that,
    required String callbackUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_String(callbackUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientFinishLoginConstMeta,
        argValues: [that, callbackUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientFinishLoginConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_finish_login",
        argNames: ["that", "callbackUrl"],
      );

  @override
  Future<NotificationContent?> crateApiChatChatClientGetNotification({
    required ChatClient that,
    required String roomId,
    required String eventId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_notification_content,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientGetNotificationConstMeta,
        argValues: [that, roomId, eventId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientGetNotificationConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_get_notification",
        argNames: ["that", "roomId", "eventId"],
      );

  @override
  Future<void> crateApiChatChatClientJoinRoom({
    required ChatClient that,
    required String roomId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientJoinRoomConstMeta,
        argValues: [that, roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientJoinRoomConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_join_room",
        argNames: ["that", "roomId"],
      );

  @override
  Future<String> crateApiChatChatClientLoginUrl({required ChatClient that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientLoginUrlConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientLoginUrlConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_login_url",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiChatChatClientLogout({required ChatClient that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientLogoutConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientLogoutConstMeta =>
      const TaskConstMeta(debugName: "ChatClient_logout", argNames: ["that"]);

  @override
  Future<void> crateApiChatChatClientMarkAsRead({required ChatClient that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientMarkAsReadConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientMarkAsReadConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_mark_as_read",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiChatChatClientOpenTimeline({
    required ChatClient that,
    required String roomId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientOpenTimelineConstMeta,
        argValues: [that, roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientOpenTimelineConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_open_timeline",
        argNames: ["that", "roomId"],
      );

  @override
  Future<bool> crateApiChatChatClientPaginateBack({
    required ChatClient that,
    required int count,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_u_16(count, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientPaginateBackConstMeta,
        argValues: [that, count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientPaginateBackConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_paginate_back",
        argNames: ["that", "count"],
      );

  @override
  Future<int> crateApiChatChatClientPersistedRefreshes({
    required ChatClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatChatClientPersistedRefreshesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientPersistedRefreshesConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_persisted_refreshes",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiChatChatClientRecover({
    required ChatClient that,
    required String recoveryKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_String(recoveryKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientRecoverConstMeta,
        argValues: [that, recoveryKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientRecoverConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_recover",
        argNames: ["that", "recoveryKey"],
      );

  @override
  Future<RecoveryStatus> crateApiChatChatClientRecoveryStatus({
    required ChatClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_recovery_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientRecoveryStatusConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientRecoveryStatusConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_recovery_status",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiChatChatClientRegisterPusher({
    required ChatClient that,
    required String pushKey,
    required String appId,
    required String gatewayUrl,
    required String deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_String(pushKey, serializer);
          sse_encode_String(appId, serializer);
          sse_encode_String(gatewayUrl, serializer);
          sse_encode_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientRegisterPusherConstMeta,
        argValues: [that, pushKey, appId, gatewayUrl, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientRegisterPusherConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_register_pusher",
        argNames: ["that", "pushKey", "appId", "gatewayUrl", "deviceName"],
      );

  @override
  Future<SessionInfo?> crateApiChatChatClientRestoreSession({
    required ChatClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientRestoreSessionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientRestoreSessionConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_restore_session",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiChatChatClientSendImage({
    required ChatClient that,
    required String filePath,
    required String mimeType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          sse_encode_String(mimeType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientSendImageConstMeta,
        argValues: [that, filePath, mimeType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientSendImageConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_send_image",
        argNames: ["that", "filePath", "mimeType"],
      );

  @override
  Future<void> crateApiChatChatClientSendText({
    required ChatClient that,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientSendTextConstMeta,
        argValues: [that, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientSendTextConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_send_text",
        argNames: ["that", "body"],
      );

  @override
  Future<void> crateApiChatChatClientShutdown({required ChatClient that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientShutdownConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientShutdownConstMeta =>
      const TaskConstMeta(debugName: "ChatClient_shutdown", argNames: ["that"]);

  @override
  Future<void> crateApiChatChatClientStartSync({required ChatClient that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientStartSyncConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientStartSyncConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_start_sync",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiChatChatClientStopSync({required ChatClient that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientStopSyncConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientStopSyncConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_stop_sync",
        argNames: ["that"],
      );

  @override
  Future<String?> crateApiChatChatClientUserId({required ChatClient that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatChatClientUserIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientUserIdConstMeta =>
      const TaskConstMeta(debugName: "ChatClient_user_id", argNames: ["that"]);

  @override
  Future<String> crateApiChatChatClientVerificationState({
    required ChatClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientVerificationStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientVerificationStateConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_verification_state",
        argNames: ["that"],
      );

  @override
  Stream<List<RoomSummary>> crateApiChatChatClientWatchRooms({
    required ChatClient that,
  }) {
    final sink = RustStreamSink<List<RoomSummary>>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
              that,
              serializer,
            );
            sse_encode_StreamSink_list_room_summary_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 25,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiChatChatClientWatchRoomsConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiChatChatClientWatchRoomsConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_watch_rooms",
        argNames: ["that", "sink"],
      );

  @override
  Stream<String> crateApiChatChatClientWatchSyncState({
    required ChatClient that,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
              that,
              serializer,
            );
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 26,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiChatChatClientWatchSyncStateConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiChatChatClientWatchSyncStateConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_watch_sync_state",
        argNames: ["that", "sink"],
      );

  @override
  Stream<List<TimelineEntry>> crateApiChatChatClientWatchTimeline({
    required ChatClient that,
  }) {
    final sink = RustStreamSink<List<TimelineEntry>>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
              that,
              serializer,
            );
            sse_encode_StreamSink_list_timeline_entry_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 27,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiChatChatClientWatchTimelineConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiChatChatClientWatchTimelineConstMeta =>
      const TaskConstMeta(
        debugName: "ChatClient_watch_timeline",
        argNames: ["that", "sink"],
      );

  @override
  Future<String> crateApiChatChatClientWhoami({required ChatClient that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatChatClientWhoamiConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatClientWhoamiConstMeta =>
      const TaskConstMeta(debugName: "ChatClient_whoami", argNames: ["that"]);

  @override
  Future<void> crateApiChatInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiChatInitLogging({required String logFile}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(logFile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChatInitLoggingConstMeta,
        argValues: [logFile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatInitLoggingConstMeta =>
      const TaskConstMeta(debugName: "init_logging", argNames: ["logFile"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ChatClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ChatClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ChatClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChatClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ChatClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChatClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ChatClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChatClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<List<RoomSummary>> dco_decode_StreamSink_list_room_summary_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<List<TimelineEntry>>
  dco_decode_StreamSink_list_timeline_entry_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChatConfig dco_decode_box_autoadd_chat_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat_config(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  MessageKind dco_decode_box_autoadd_message_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_message_kind(raw);
  }

  @protected
  NotificationContent dco_decode_box_autoadd_notification_content(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_notification_content(raw);
  }

  @protected
  SessionInfo dco_decode_box_autoadd_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_session_info(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ChatConfig dco_decode_chat_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ChatConfig(
      homeserverUrl: dco_decode_String(arr[0]),
      dataDir: dco_decode_String(arr[1]),
      cacheDir: dco_decode_String(arr[2]),
      storeKey: dco_decode_list_prim_u_8_strict(arr[3]),
      clientName: dco_decode_String(arr[4]),
      clientUri: dco_decode_String(arr[5]),
      redirectUri: dco_decode_String(arr[6]),
      devRootCertificatePem: dco_decode_opt_String(arr[7]),
      crossProcessHolder: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RoomSummary> dco_decode_list_room_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_room_summary).toList();
  }

  @protected
  List<TimelineEntry> dco_decode_list_timeline_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_timeline_entry).toList();
  }

  @protected
  MessageKind dco_decode_message_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MessageKind_Text(body: dco_decode_String(raw[1]));
      case 1:
        return MessageKind_Image(
          body: dco_decode_String(raw[1]),
          sourceJson: dco_decode_String(raw[2]),
          width: dco_decode_opt_box_autoadd_u_32(raw[3]),
          height: dco_decode_opt_box_autoadd_u_32(raw[4]),
        );
      case 2:
        return MessageKind_UnableToDecrypt();
      case 3:
        return MessageKind_Redacted();
      case 4:
        return MessageKind_Other(description: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  NotificationContent dco_decode_notification_content(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NotificationContent(
      roomName: dco_decode_String(arr[0]),
      senderName: dco_decode_opt_String(arr[1]),
      body: dco_decode_String(arr[2]),
      isDirect: dco_decode_bool(arr[3]),
      isEncrypted: dco_decode_opt_box_autoadd_bool(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  NotificationContent? dco_decode_opt_box_autoadd_notification_content(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_notification_content(raw);
  }

  @protected
  SessionInfo? dco_decode_opt_box_autoadd_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_session_info(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  RecoveryStatus dco_decode_recovery_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RecoveryStatus.values[raw as int];
  }

  @protected
  RoomSummary dco_decode_room_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RoomSummary(
      roomId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      isEncrypted: dco_decode_bool(arr[2]),
      isDirect: dco_decode_bool(arr[3]),
      isInvite: dco_decode_bool(arr[4]),
      unreadCount: dco_decode_u_64(arr[5]),
      latestTimestampMs: dco_decode_opt_box_autoadd_i_64(arr[6]),
    );
  }

  @protected
  SessionInfo dco_decode_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SessionInfo(
      userId: dco_decode_String(arr[0]),
      deviceId: dco_decode_String(arr[1]),
    );
  }

  @protected
  TimelineEntry dco_decode_timeline_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return TimelineEntry_Message(
          uniqueId: dco_decode_String(raw[1]),
          eventId: dco_decode_opt_String(raw[2]),
          senderId: dco_decode_String(raw[3]),
          senderName: dco_decode_opt_String(raw[4]),
          timestampMs: dco_decode_i_64(raw[5]),
          isOwn: dco_decode_bool(raw[6]),
          isSending: dco_decode_bool(raw[7]),
          isFailed: dco_decode_bool(raw[8]),
          kind: dco_decode_box_autoadd_message_kind(raw[9]),
        );
      case 1:
        return TimelineEntry_State(
          uniqueId: dco_decode_String(raw[1]),
          description: dco_decode_String(raw[2]),
        );
      case 2:
        return TimelineEntry_DayDivider(
          uniqueId: dco_decode_String(raw[1]),
          timestampMs: dco_decode_i_64(raw[2]),
        );
      case 3:
        return TimelineEntry_ReadMarker(uniqueId: dco_decode_String(raw[1]));
      case 4:
        return TimelineEntry_TimelineStart(uniqueId: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ChatClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ChatClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ChatClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ChatClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ChatClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ChatClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<List<RoomSummary>> sse_decode_StreamSink_list_room_summary_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<List<TimelineEntry>>
  sse_decode_StreamSink_list_timeline_entry_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  ChatConfig sse_decode_box_autoadd_chat_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat_config(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  MessageKind sse_decode_box_autoadd_message_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_message_kind(deserializer));
  }

  @protected
  NotificationContent sse_decode_box_autoadd_notification_content(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_notification_content(deserializer));
  }

  @protected
  SessionInfo sse_decode_box_autoadd_session_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_session_info(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  ChatConfig sse_decode_chat_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_homeserverUrl = sse_decode_String(deserializer);
    var var_dataDir = sse_decode_String(deserializer);
    var var_cacheDir = sse_decode_String(deserializer);
    var var_storeKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_clientName = sse_decode_String(deserializer);
    var var_clientUri = sse_decode_String(deserializer);
    var var_redirectUri = sse_decode_String(deserializer);
    var var_devRootCertificatePem = sse_decode_opt_String(deserializer);
    var var_crossProcessHolder = sse_decode_opt_String(deserializer);
    return ChatConfig(
      homeserverUrl: var_homeserverUrl,
      dataDir: var_dataDir,
      cacheDir: var_cacheDir,
      storeKey: var_storeKey,
      clientName: var_clientName,
      clientUri: var_clientUri,
      redirectUri: var_redirectUri,
      devRootCertificatePem: var_devRootCertificatePem,
      crossProcessHolder: var_crossProcessHolder,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RoomSummary> sse_decode_list_room_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RoomSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_room_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<TimelineEntry> sse_decode_list_timeline_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TimelineEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_timeline_entry(deserializer));
    }
    return ans_;
  }

  @protected
  MessageKind sse_decode_message_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_body = sse_decode_String(deserializer);
        return MessageKind_Text(body: var_body);
      case 1:
        var var_body = sse_decode_String(deserializer);
        var var_sourceJson = sse_decode_String(deserializer);
        var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
        var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
        return MessageKind_Image(
          body: var_body,
          sourceJson: var_sourceJson,
          width: var_width,
          height: var_height,
        );
      case 2:
        return MessageKind_UnableToDecrypt();
      case 3:
        return MessageKind_Redacted();
      case 4:
        var var_description = sse_decode_String(deserializer);
        return MessageKind_Other(description: var_description);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  NotificationContent sse_decode_notification_content(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roomName = sse_decode_String(deserializer);
    var var_senderName = sse_decode_opt_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_isDirect = sse_decode_bool(deserializer);
    var var_isEncrypted = sse_decode_opt_box_autoadd_bool(deserializer);
    return NotificationContent(
      roomName: var_roomName,
      senderName: var_senderName,
      body: var_body,
      isDirect: var_isDirect,
      isEncrypted: var_isEncrypted,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NotificationContent? sse_decode_opt_box_autoadd_notification_content(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_notification_content(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionInfo? sse_decode_opt_box_autoadd_session_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_session_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RecoveryStatus sse_decode_recovery_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RecoveryStatus.values[inner];
  }

  @protected
  RoomSummary sse_decode_room_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roomId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_isEncrypted = sse_decode_bool(deserializer);
    var var_isDirect = sse_decode_bool(deserializer);
    var var_isInvite = sse_decode_bool(deserializer);
    var var_unreadCount = sse_decode_u_64(deserializer);
    var var_latestTimestampMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    return RoomSummary(
      roomId: var_roomId,
      displayName: var_displayName,
      isEncrypted: var_isEncrypted,
      isDirect: var_isDirect,
      isInvite: var_isInvite,
      unreadCount: var_unreadCount,
      latestTimestampMs: var_latestTimestampMs,
    );
  }

  @protected
  SessionInfo sse_decode_session_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    return SessionInfo(userId: var_userId, deviceId: var_deviceId);
  }

  @protected
  TimelineEntry sse_decode_timeline_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_uniqueId = sse_decode_String(deserializer);
        var var_eventId = sse_decode_opt_String(deserializer);
        var var_senderId = sse_decode_String(deserializer);
        var var_senderName = sse_decode_opt_String(deserializer);
        var var_timestampMs = sse_decode_i_64(deserializer);
        var var_isOwn = sse_decode_bool(deserializer);
        var var_isSending = sse_decode_bool(deserializer);
        var var_isFailed = sse_decode_bool(deserializer);
        var var_kind = sse_decode_box_autoadd_message_kind(deserializer);
        return TimelineEntry_Message(
          uniqueId: var_uniqueId,
          eventId: var_eventId,
          senderId: var_senderId,
          senderName: var_senderName,
          timestampMs: var_timestampMs,
          isOwn: var_isOwn,
          isSending: var_isSending,
          isFailed: var_isFailed,
          kind: var_kind,
        );
      case 1:
        var var_uniqueId = sse_decode_String(deserializer);
        var var_description = sse_decode_String(deserializer);
        return TimelineEntry_State(
          uniqueId: var_uniqueId,
          description: var_description,
        );
      case 2:
        var var_uniqueId = sse_decode_String(deserializer);
        var var_timestampMs = sse_decode_i_64(deserializer);
        return TimelineEntry_DayDivider(
          uniqueId: var_uniqueId,
          timestampMs: var_timestampMs,
        );
      case 3:
        var var_uniqueId = sse_decode_String(deserializer);
        return TimelineEntry_ReadMarker(uniqueId: var_uniqueId);
      case 4:
        var var_uniqueId = sse_decode_String(deserializer);
        return TimelineEntry_TimelineStart(uniqueId: var_uniqueId);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    ChatClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ChatClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    ChatClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ChatClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    ChatClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ChatClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_room_summary_Sse(
    RustStreamSink<List<RoomSummary>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_room_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_timeline_entry_Sse(
    RustStreamSink<List<TimelineEntry>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_timeline_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_chat_config(
    ChatConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_message_kind(
    MessageKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_message_kind(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_notification_content(
    NotificationContent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_notification_content(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_session_info(
    SessionInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_chat_config(ChatConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.homeserverUrl, serializer);
    sse_encode_String(self.dataDir, serializer);
    sse_encode_String(self.cacheDir, serializer);
    sse_encode_list_prim_u_8_strict(self.storeKey, serializer);
    sse_encode_String(self.clientName, serializer);
    sse_encode_String(self.clientUri, serializer);
    sse_encode_String(self.redirectUri, serializer);
    sse_encode_opt_String(self.devRootCertificatePem, serializer);
    sse_encode_opt_String(self.crossProcessHolder, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_room_summary(
    List<RoomSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_room_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_timeline_entry(
    List<TimelineEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_timeline_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_message_kind(MessageKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MessageKind_Text(body: final body):
        sse_encode_i_32(0, serializer);
        sse_encode_String(body, serializer);
      case MessageKind_Image(
        body: final body,
        sourceJson: final sourceJson,
        width: final width,
        height: final height,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(body, serializer);
        sse_encode_String(sourceJson, serializer);
        sse_encode_opt_box_autoadd_u_32(width, serializer);
        sse_encode_opt_box_autoadd_u_32(height, serializer);
      case MessageKind_UnableToDecrypt():
        sse_encode_i_32(2, serializer);
      case MessageKind_Redacted():
        sse_encode_i_32(3, serializer);
      case MessageKind_Other(description: final description):
        sse_encode_i_32(4, serializer);
        sse_encode_String(description, serializer);
    }
  }

  @protected
  void sse_encode_notification_content(
    NotificationContent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.roomName, serializer);
    sse_encode_opt_String(self.senderName, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_bool(self.isDirect, serializer);
    sse_encode_opt_box_autoadd_bool(self.isEncrypted, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_notification_content(
    NotificationContent? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_notification_content(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_session_info(
    SessionInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_session_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_recovery_status(
    RecoveryStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_room_summary(RoomSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.roomId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_bool(self.isEncrypted, serializer);
    sse_encode_bool(self.isDirect, serializer);
    sse_encode_bool(self.isInvite, serializer);
    sse_encode_u_64(self.unreadCount, serializer);
    sse_encode_opt_box_autoadd_i_64(self.latestTimestampMs, serializer);
  }

  @protected
  void sse_encode_session_info(SessionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.deviceId, serializer);
  }

  @protected
  void sse_encode_timeline_entry(TimelineEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case TimelineEntry_Message(
        uniqueId: final uniqueId,
        eventId: final eventId,
        senderId: final senderId,
        senderName: final senderName,
        timestampMs: final timestampMs,
        isOwn: final isOwn,
        isSending: final isSending,
        isFailed: final isFailed,
        kind: final kind,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(uniqueId, serializer);
        sse_encode_opt_String(eventId, serializer);
        sse_encode_String(senderId, serializer);
        sse_encode_opt_String(senderName, serializer);
        sse_encode_i_64(timestampMs, serializer);
        sse_encode_bool(isOwn, serializer);
        sse_encode_bool(isSending, serializer);
        sse_encode_bool(isFailed, serializer);
        sse_encode_box_autoadd_message_kind(kind, serializer);
      case TimelineEntry_State(
        uniqueId: final uniqueId,
        description: final description,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(uniqueId, serializer);
        sse_encode_String(description, serializer);
      case TimelineEntry_DayDivider(
        uniqueId: final uniqueId,
        timestampMs: final timestampMs,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(uniqueId, serializer);
        sse_encode_i_64(timestampMs, serializer);
      case TimelineEntry_ReadMarker(uniqueId: final uniqueId):
        sse_encode_i_32(3, serializer);
        sse_encode_String(uniqueId, serializer);
      case TimelineEntry_TimelineStart(uniqueId: final uniqueId):
        sse_encode_i_32(4, serializer);
        sse_encode_String(uniqueId, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ChatClientImpl extends RustOpaque implements ChatClient {
  // Not to be used by end users
  ChatClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ChatClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ChatClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ChatClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ChatClientPtr,
  );

  /// Creates (or reuses) an encrypted DM with the given user.
  Future<String> createDm({required String userId}) => RustLib.instance.api
      .crateApiChatChatClientCreateDm(that: this, userId: userId);

  /// Enables key backup + secret storage and returns the recovery key
  /// that the user has to write down.
  Future<String> enableRecovery() =>
      RustLib.instance.api.crateApiChatChatClientEnableRecovery(that: this);

  /// Downloads (and decrypts) authenticated media referenced by a timeline item.
  Future<Uint8List> fetchMedia({required String sourceJson}) => RustLib
      .instance
      .api
      .crateApiChatChatClientFetchMedia(that: this, sourceJson: sourceJson);

  /// Completes the OAuth flow with the redirect URL received by the app.
  Future<SessionInfo> finishLogin({required String callbackUrl}) => RustLib
      .instance
      .api
      .crateApiChatChatClientFinishLogin(that: this, callbackUrl: callbackUrl);

  /// Resolves and decrypts a pushed event (`event_id_only` payload) the way
  /// the Android FCM handler / iOS Notification Service Extension would.
  Future<NotificationContent?> getNotification({
    required String roomId,
    required String eventId,
  }) => RustLib.instance.api.crateApiChatChatClientGetNotification(
    that: this,
    roomId: roomId,
    eventId: eventId,
  );

  Future<void> joinRoom({required String roomId}) => RustLib.instance.api
      .crateApiChatChatClientJoinRoom(that: this, roomId: roomId);

  /// Starts an OAuth 2.0 authorization code flow with PKCE against MAS
  /// (dynamic client registration) and returns the URL for the system
  /// browser.
  Future<String> loginUrl() =>
      RustLib.instance.api.crateApiChatChatClientLoginUrl(that: this);

  Future<void> logout() =>
      RustLib.instance.api.crateApiChatChatClientLogout(that: this);

  Future<void> markAsRead() =>
      RustLib.instance.api.crateApiChatChatClientMarkAsRead(that: this);

  /// Opens the timeline of a room and streams snapshots of its items.
  /// Opens the timeline of a room; subsequent timeline calls act on it.
  Future<void> openTimeline({required String roomId}) => RustLib.instance.api
      .crateApiChatChatClientOpenTimeline(that: this, roomId: roomId);

  /// Loads older events; returns true when the start of the room was reached.
  Future<bool> paginateBack({required int count}) => RustLib.instance.api
      .crateApiChatChatClientPaginateBack(that: this, count: count);

  /// Number of token refreshes persisted by this client instance.
  Future<int> persistedRefreshes() =>
      RustLib.instance.api.crateApiChatChatClientPersistedRefreshes(that: this);

  /// Restores cross-signing and the key backup on a new device.
  Future<void> recover({required String recoveryKey}) => RustLib.instance.api
      .crateApiChatChatClientRecover(that: this, recoveryKey: recoveryKey);

  Future<RecoveryStatus> recoveryStatus() =>
      RustLib.instance.api.crateApiChatChatClientRecoveryStatus(that: this);

  /// Registers an HTTP pusher (Sygnal) with `event_id_only` payloads.
  Future<void> registerPusher({
    required String pushKey,
    required String appId,
    required String gatewayUrl,
    required String deviceName,
  }) => RustLib.instance.api.crateApiChatChatClientRegisterPusher(
    that: this,
    pushKey: pushKey,
    appId: appId,
    gatewayUrl: gatewayUrl,
    deviceName: deviceName,
  );

  /// Restores a previously persisted session from the encrypted store.
  Future<SessionInfo?> restoreSession() =>
      RustLib.instance.api.crateApiChatChatClientRestoreSession(that: this);

  Future<void> sendImage({
    required String filePath,
    required String mimeType,
  }) => RustLib.instance.api.crateApiChatChatClientSendImage(
    that: this,
    filePath: filePath,
    mimeType: mimeType,
  );

  Future<void> sendText({required String body}) => RustLib.instance.api
      .crateApiChatChatClientSendText(that: this, body: body);

  /// Stops all background work so that another client may open the store.
  Future<void> shutdown() =>
      RustLib.instance.api.crateApiChatChatClientShutdown(that: this);

  /// Starts the sync service (Simplified Sliding Sync + encryption sync).
  Future<void> startSync() =>
      RustLib.instance.api.crateApiChatChatClientStartSync(that: this);

  Future<void> stopSync() =>
      RustLib.instance.api.crateApiChatChatClientStopSync(that: this);

  Future<String?> userId() =>
      RustLib.instance.api.crateApiChatChatClientUserId(that: this);

  /// `verified` once this device is cross-signed (e.g. after recovery).
  Future<String> verificationState() =>
      RustLib.instance.api.crateApiChatChatClientVerificationState(that: this);

  /// Streams the complete room list (joined + invited) as snapshots,
  /// driven by `RoomListService` diffs.
  Stream<List<RoomSummary>> watchRooms() =>
      RustLib.instance.api.crateApiChatChatClientWatchRooms(that: this);

  /// Streams the sync service state as text (`idle`, `running`, `terminated`, `error`, `offline`).
  Stream<String> watchSyncState() =>
      RustLib.instance.api.crateApiChatChatClientWatchSyncState(that: this);

  /// Streams snapshots of the open timeline.
  Stream<List<TimelineEntry>> watchTimeline() =>
      RustLib.instance.api.crateApiChatChatClientWatchTimeline(that: this);

  /// Authenticated round trip (`/whoami`); refreshes an expired access token.
  Future<String> whoami() =>
      RustLib.instance.api.crateApiChatChatClientWhoami(that: this);
}
