// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/client.dart';
import 'api/encryption.dart';
import 'api/error.dart';
import 'api/lifecycle.dart';
import 'api/logging.dart';
import 'api/notifications.dart';
import 'api/room.dart';
import 'api/rooms.dart';
import 'api/threads.dart';
import 'api/timeline.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ChatClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ChatThreadListPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ChatTimelinePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ChatClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    dynamic raw,
  );

  @protected
  ChatThreadList
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    dynamic raw,
  );

  @protected
  ChatTimeline
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    dynamic raw,
  );

  @protected
  ChatClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    dynamic raw,
  );

  @protected
  ChatThreadList
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    dynamic raw,
  );

  @protected
  ChatTimeline
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    dynamic raw,
  );

  @protected
  ChatClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    dynamic raw,
  );

  @protected
  ChatThreadList
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    dynamic raw,
  );

  @protected
  ChatTimeline
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<RoomListDiff>>
  dco_decode_StreamSink_list_room_list_diff_Sse(dynamic raw);

  @protected
  RustStreamSink<List<Sender>> dco_decode_StreamSink_list_sender_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<ThreadListDiff>>
  dco_decode_StreamSink_list_thread_list_diff_Sse(dynamic raw);

  @protected
  RustStreamSink<List<TimelineDiff>>
  dco_decode_StreamSink_list_timeline_diff_Sse(dynamic raw);

  @protected
  RustStreamSink<SessionState> dco_decode_StreamSink_session_state_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SyncStatus> dco_decode_StreamSink_sync_status_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ChatConfig dco_decode_box_autoadd_chat_config(dynamic raw);

  @protected
  EventItem dco_decode_box_autoadd_event_item(dynamic raw);

  @protected
  EventKey dco_decode_box_autoadd_event_key(dynamic raw);

  @protected
  ImageAttachment dco_decode_box_autoadd_image_attachment(dynamic raw);

  @protected
  ImageThumbnail dco_decode_box_autoadd_image_thumbnail(dynamic raw);

  @protected
  LatestEvent dco_decode_box_autoadd_latest_event(dynamic raw);

  @protected
  MessagePreview dco_decode_box_autoadd_message_preview(dynamic raw);

  @protected
  NotificationContent dco_decode_box_autoadd_notification_content(dynamic raw);

  @protected
  NotificationMode dco_decode_box_autoadd_notification_mode(dynamic raw);

  @protected
  ReplyPreview dco_decode_box_autoadd_reply_preview(dynamic raw);

  @protected
  RoomSummary dco_decode_box_autoadd_room_summary(dynamic raw);

  @protected
  Sender dco_decode_box_autoadd_sender(dynamic raw);

  @protected
  SessionInfo dco_decode_box_autoadd_session_info(dynamic raw);

  @protected
  ThreadEvent dco_decode_box_autoadd_thread_event(dynamic raw);

  @protected
  ThreadInfo dco_decode_box_autoadd_thread_info(dynamic raw);

  @protected
  ThreadSummary dco_decode_box_autoadd_thread_summary(dynamic raw);

  @protected
  TimelineItem dco_decode_box_autoadd_timeline_item(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  UploadProgress dco_decode_box_autoadd_upload_progress(dynamic raw);

  @protected
  ChatConfig dco_decode_chat_config(dynamic raw);

  @protected
  ChatError dco_decode_chat_error(dynamic raw);

  @protected
  EventContent dco_decode_event_content(dynamic raw);

  @protected
  EventItem dco_decode_event_item(dynamic raw);

  @protected
  EventKey dco_decode_event_key(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageAttachment dco_decode_image_attachment(dynamic raw);

  @protected
  ImageThumbnail dco_decode_image_thumbnail(dynamic raw);

  @protected
  LatestEvent dco_decode_latest_event(dynamic raw);

  @protected
  List<Member> dco_decode_list_member(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Reaction> dco_decode_list_reaction(dynamic raw);

  @protected
  List<RoomListDiff> dco_decode_list_room_list_diff(dynamic raw);

  @protected
  List<RoomSummary> dco_decode_list_room_summary(dynamic raw);

  @protected
  List<Sender> dco_decode_list_sender(dynamic raw);

  @protected
  List<ThreadInfo> dco_decode_list_thread_info(dynamic raw);

  @protected
  List<ThreadListDiff> dco_decode_list_thread_list_diff(dynamic raw);

  @protected
  List<TimelineDiff> dco_decode_list_timeline_diff(dynamic raw);

  @protected
  List<TimelineItem> dco_decode_list_timeline_item(dynamic raw);

  @protected
  LogLevel dco_decode_log_level(dynamic raw);

  @protected
  Member dco_decode_member(dynamic raw);

  @protected
  MemberRole dco_decode_member_role(dynamic raw);

  @protected
  MemberState dco_decode_member_state(dynamic raw);

  @protected
  Membership dco_decode_membership(dynamic raw);

  @protected
  MembershipKind dco_decode_membership_kind(dynamic raw);

  @protected
  MessagePreview dco_decode_message_preview(dynamic raw);

  @protected
  NotificationContent dco_decode_notification_content(dynamic raw);

  @protected
  NotificationMode dco_decode_notification_mode(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ImageThumbnail? dco_decode_opt_box_autoadd_image_thumbnail(dynamic raw);

  @protected
  LatestEvent? dco_decode_opt_box_autoadd_latest_event(dynamic raw);

  @protected
  MessagePreview? dco_decode_opt_box_autoadd_message_preview(dynamic raw);

  @protected
  NotificationContent? dco_decode_opt_box_autoadd_notification_content(
    dynamic raw,
  );

  @protected
  NotificationMode? dco_decode_opt_box_autoadd_notification_mode(dynamic raw);

  @protected
  ReplyPreview? dco_decode_opt_box_autoadd_reply_preview(dynamic raw);

  @protected
  Sender? dco_decode_opt_box_autoadd_sender(dynamic raw);

  @protected
  SessionInfo? dco_decode_opt_box_autoadd_session_info(dynamic raw);

  @protected
  ThreadEvent? dco_decode_opt_box_autoadd_thread_event(dynamic raw);

  @protected
  ThreadSummary? dco_decode_opt_box_autoadd_thread_summary(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  UploadProgress? dco_decode_opt_box_autoadd_upload_progress(dynamic raw);

  @protected
  Reaction dco_decode_reaction(dynamic raw);

  @protected
  RecoveryStatus dco_decode_recovery_status(dynamic raw);

  @protected
  ReplyPreview dco_decode_reply_preview(dynamic raw);

  @protected
  RoomFilter dco_decode_room_filter(dynamic raw);

  @protected
  RoomKind dco_decode_room_kind(dynamic raw);

  @protected
  RoomListDiff dco_decode_room_list_diff(dynamic raw);

  @protected
  RoomNotificationSettings dco_decode_room_notification_settings(dynamic raw);

  @protected
  RoomSummary dco_decode_room_summary(dynamic raw);

  @protected
  SendState dco_decode_send_state(dynamic raw);

  @protected
  Sender dco_decode_sender(dynamic raw);

  @protected
  SessionInfo dco_decode_session_info(dynamic raw);

  @protected
  SessionState dco_decode_session_state(dynamic raw);

  @protected
  SyncStatus dco_decode_sync_status(dynamic raw);

  @protected
  ThreadEvent dco_decode_thread_event(dynamic raw);

  @protected
  ThreadInfo dco_decode_thread_info(dynamic raw);

  @protected
  ThreadListDiff dco_decode_thread_list_diff(dynamic raw);

  @protected
  ThreadSummary dco_decode_thread_summary(dynamic raw);

  @protected
  TimelineDiff dco_decode_timeline_diff(dynamic raw);

  @protected
  TimelineItem dco_decode_timeline_item(dynamic raw);

  @protected
  TimelineItemKind dco_decode_timeline_item_kind(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UploadProgress dco_decode_upload_progress(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ChatClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    SseDeserializer deserializer,
  );

  @protected
  ChatThreadList
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    SseDeserializer deserializer,
  );

  @protected
  ChatTimeline
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    SseDeserializer deserializer,
  );

  @protected
  ChatClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    SseDeserializer deserializer,
  );

  @protected
  ChatThreadList
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    SseDeserializer deserializer,
  );

  @protected
  ChatTimeline
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    SseDeserializer deserializer,
  );

  @protected
  ChatClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    SseDeserializer deserializer,
  );

  @protected
  ChatThreadList
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    SseDeserializer deserializer,
  );

  @protected
  ChatTimeline
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<RoomListDiff>>
  sse_decode_StreamSink_list_room_list_diff_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<List<Sender>> sse_decode_StreamSink_list_sender_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<ThreadListDiff>>
  sse_decode_StreamSink_list_thread_list_diff_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<List<TimelineDiff>>
  sse_decode_StreamSink_list_timeline_diff_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<SessionState> sse_decode_StreamSink_session_state_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncStatus> sse_decode_StreamSink_sync_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ChatConfig sse_decode_box_autoadd_chat_config(SseDeserializer deserializer);

  @protected
  EventItem sse_decode_box_autoadd_event_item(SseDeserializer deserializer);

  @protected
  EventKey sse_decode_box_autoadd_event_key(SseDeserializer deserializer);

  @protected
  ImageAttachment sse_decode_box_autoadd_image_attachment(
    SseDeserializer deserializer,
  );

  @protected
  ImageThumbnail sse_decode_box_autoadd_image_thumbnail(
    SseDeserializer deserializer,
  );

  @protected
  LatestEvent sse_decode_box_autoadd_latest_event(SseDeserializer deserializer);

  @protected
  MessagePreview sse_decode_box_autoadd_message_preview(
    SseDeserializer deserializer,
  );

  @protected
  NotificationContent sse_decode_box_autoadd_notification_content(
    SseDeserializer deserializer,
  );

  @protected
  NotificationMode sse_decode_box_autoadd_notification_mode(
    SseDeserializer deserializer,
  );

  @protected
  ReplyPreview sse_decode_box_autoadd_reply_preview(
    SseDeserializer deserializer,
  );

  @protected
  RoomSummary sse_decode_box_autoadd_room_summary(SseDeserializer deserializer);

  @protected
  Sender sse_decode_box_autoadd_sender(SseDeserializer deserializer);

  @protected
  SessionInfo sse_decode_box_autoadd_session_info(SseDeserializer deserializer);

  @protected
  ThreadEvent sse_decode_box_autoadd_thread_event(SseDeserializer deserializer);

  @protected
  ThreadInfo sse_decode_box_autoadd_thread_info(SseDeserializer deserializer);

  @protected
  ThreadSummary sse_decode_box_autoadd_thread_summary(
    SseDeserializer deserializer,
  );

  @protected
  TimelineItem sse_decode_box_autoadd_timeline_item(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UploadProgress sse_decode_box_autoadd_upload_progress(
    SseDeserializer deserializer,
  );

  @protected
  ChatConfig sse_decode_chat_config(SseDeserializer deserializer);

  @protected
  ChatError sse_decode_chat_error(SseDeserializer deserializer);

  @protected
  EventContent sse_decode_event_content(SseDeserializer deserializer);

  @protected
  EventItem sse_decode_event_item(SseDeserializer deserializer);

  @protected
  EventKey sse_decode_event_key(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageAttachment sse_decode_image_attachment(SseDeserializer deserializer);

  @protected
  ImageThumbnail sse_decode_image_thumbnail(SseDeserializer deserializer);

  @protected
  LatestEvent sse_decode_latest_event(SseDeserializer deserializer);

  @protected
  List<Member> sse_decode_list_member(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Reaction> sse_decode_list_reaction(SseDeserializer deserializer);

  @protected
  List<RoomListDiff> sse_decode_list_room_list_diff(
    SseDeserializer deserializer,
  );

  @protected
  List<RoomSummary> sse_decode_list_room_summary(SseDeserializer deserializer);

  @protected
  List<Sender> sse_decode_list_sender(SseDeserializer deserializer);

  @protected
  List<ThreadInfo> sse_decode_list_thread_info(SseDeserializer deserializer);

  @protected
  List<ThreadListDiff> sse_decode_list_thread_list_diff(
    SseDeserializer deserializer,
  );

  @protected
  List<TimelineDiff> sse_decode_list_timeline_diff(
    SseDeserializer deserializer,
  );

  @protected
  List<TimelineItem> sse_decode_list_timeline_item(
    SseDeserializer deserializer,
  );

  @protected
  LogLevel sse_decode_log_level(SseDeserializer deserializer);

  @protected
  Member sse_decode_member(SseDeserializer deserializer);

  @protected
  MemberRole sse_decode_member_role(SseDeserializer deserializer);

  @protected
  MemberState sse_decode_member_state(SseDeserializer deserializer);

  @protected
  Membership sse_decode_membership(SseDeserializer deserializer);

  @protected
  MembershipKind sse_decode_membership_kind(SseDeserializer deserializer);

  @protected
  MessagePreview sse_decode_message_preview(SseDeserializer deserializer);

  @protected
  NotificationContent sse_decode_notification_content(
    SseDeserializer deserializer,
  );

  @protected
  NotificationMode sse_decode_notification_mode(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ImageThumbnail? sse_decode_opt_box_autoadd_image_thumbnail(
    SseDeserializer deserializer,
  );

  @protected
  LatestEvent? sse_decode_opt_box_autoadd_latest_event(
    SseDeserializer deserializer,
  );

  @protected
  MessagePreview? sse_decode_opt_box_autoadd_message_preview(
    SseDeserializer deserializer,
  );

  @protected
  NotificationContent? sse_decode_opt_box_autoadd_notification_content(
    SseDeserializer deserializer,
  );

  @protected
  NotificationMode? sse_decode_opt_box_autoadd_notification_mode(
    SseDeserializer deserializer,
  );

  @protected
  ReplyPreview? sse_decode_opt_box_autoadd_reply_preview(
    SseDeserializer deserializer,
  );

  @protected
  Sender? sse_decode_opt_box_autoadd_sender(SseDeserializer deserializer);

  @protected
  SessionInfo? sse_decode_opt_box_autoadd_session_info(
    SseDeserializer deserializer,
  );

  @protected
  ThreadEvent? sse_decode_opt_box_autoadd_thread_event(
    SseDeserializer deserializer,
  );

  @protected
  ThreadSummary? sse_decode_opt_box_autoadd_thread_summary(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UploadProgress? sse_decode_opt_box_autoadd_upload_progress(
    SseDeserializer deserializer,
  );

  @protected
  Reaction sse_decode_reaction(SseDeserializer deserializer);

  @protected
  RecoveryStatus sse_decode_recovery_status(SseDeserializer deserializer);

  @protected
  ReplyPreview sse_decode_reply_preview(SseDeserializer deserializer);

  @protected
  RoomFilter sse_decode_room_filter(SseDeserializer deserializer);

  @protected
  RoomKind sse_decode_room_kind(SseDeserializer deserializer);

  @protected
  RoomListDiff sse_decode_room_list_diff(SseDeserializer deserializer);

  @protected
  RoomNotificationSettings sse_decode_room_notification_settings(
    SseDeserializer deserializer,
  );

  @protected
  RoomSummary sse_decode_room_summary(SseDeserializer deserializer);

  @protected
  SendState sse_decode_send_state(SseDeserializer deserializer);

  @protected
  Sender sse_decode_sender(SseDeserializer deserializer);

  @protected
  SessionInfo sse_decode_session_info(SseDeserializer deserializer);

  @protected
  SessionState sse_decode_session_state(SseDeserializer deserializer);

  @protected
  SyncStatus sse_decode_sync_status(SseDeserializer deserializer);

  @protected
  ThreadEvent sse_decode_thread_event(SseDeserializer deserializer);

  @protected
  ThreadInfo sse_decode_thread_info(SseDeserializer deserializer);

  @protected
  ThreadListDiff sse_decode_thread_list_diff(SseDeserializer deserializer);

  @protected
  ThreadSummary sse_decode_thread_summary(SseDeserializer deserializer);

  @protected
  TimelineDiff sse_decode_timeline_diff(SseDeserializer deserializer);

  @protected
  TimelineItem sse_decode_timeline_item(SseDeserializer deserializer);

  @protected
  TimelineItemKind sse_decode_timeline_item_kind(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UploadProgress sse_decode_upload_progress(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    ChatClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    ChatThreadList self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    ChatTimeline self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    ChatClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    ChatThreadList self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    ChatTimeline self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    ChatClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    ChatThreadList self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    ChatTimeline self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_room_list_diff_Sse(
    RustStreamSink<List<RoomListDiff>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_sender_Sse(
    RustStreamSink<List<Sender>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_thread_list_diff_Sse(
    RustStreamSink<List<ThreadListDiff>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_timeline_diff_Sse(
    RustStreamSink<List<TimelineDiff>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_session_state_Sse(
    RustStreamSink<SessionState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_status_Sse(
    RustStreamSink<SyncStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_chat_config(
    ChatConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_event_item(
    EventItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_event_key(
    EventKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_attachment(
    ImageAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_thumbnail(
    ImageThumbnail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_latest_event(
    LatestEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_message_preview(
    MessagePreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_notification_content(
    NotificationContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_notification_mode(
    NotificationMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reply_preview(
    ReplyPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_room_summary(
    RoomSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sender(Sender self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_session_info(
    SessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thread_event(
    ThreadEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thread_info(
    ThreadInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thread_summary(
    ThreadSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_timeline_item(
    TimelineItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_upload_progress(
    UploadProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_config(ChatConfig self, SseSerializer serializer);

  @protected
  void sse_encode_chat_error(ChatError self, SseSerializer serializer);

  @protected
  void sse_encode_event_content(EventContent self, SseSerializer serializer);

  @protected
  void sse_encode_event_item(EventItem self, SseSerializer serializer);

  @protected
  void sse_encode_event_key(EventKey self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_attachment(
    ImageAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_image_thumbnail(
    ImageThumbnail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_latest_event(LatestEvent self, SseSerializer serializer);

  @protected
  void sse_encode_list_member(List<Member> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reaction(List<Reaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_room_list_diff(
    List<RoomListDiff> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_room_summary(
    List<RoomSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sender(List<Sender> self, SseSerializer serializer);

  @protected
  void sse_encode_list_thread_info(
    List<ThreadInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_thread_list_diff(
    List<ThreadListDiff> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_timeline_diff(
    List<TimelineDiff> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_timeline_item(
    List<TimelineItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_level(LogLevel self, SseSerializer serializer);

  @protected
  void sse_encode_member(Member self, SseSerializer serializer);

  @protected
  void sse_encode_member_role(MemberRole self, SseSerializer serializer);

  @protected
  void sse_encode_member_state(MemberState self, SseSerializer serializer);

  @protected
  void sse_encode_membership(Membership self, SseSerializer serializer);

  @protected
  void sse_encode_membership_kind(
    MembershipKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_preview(
    MessagePreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_content(
    NotificationContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_mode(
    NotificationMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_image_thumbnail(
    ImageThumbnail? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_latest_event(
    LatestEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_message_preview(
    MessagePreview? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_notification_content(
    NotificationContent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_notification_mode(
    NotificationMode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reply_preview(
    ReplyPreview? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sender(
    Sender? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_info(
    SessionInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_thread_event(
    ThreadEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_thread_summary(
    ThreadSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_upload_progress(
    UploadProgress? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reaction(Reaction self, SseSerializer serializer);

  @protected
  void sse_encode_recovery_status(
    RecoveryStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reply_preview(ReplyPreview self, SseSerializer serializer);

  @protected
  void sse_encode_room_filter(RoomFilter self, SseSerializer serializer);

  @protected
  void sse_encode_room_kind(RoomKind self, SseSerializer serializer);

  @protected
  void sse_encode_room_list_diff(RoomListDiff self, SseSerializer serializer);

  @protected
  void sse_encode_room_notification_settings(
    RoomNotificationSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_room_summary(RoomSummary self, SseSerializer serializer);

  @protected
  void sse_encode_send_state(SendState self, SseSerializer serializer);

  @protected
  void sse_encode_sender(Sender self, SseSerializer serializer);

  @protected
  void sse_encode_session_info(SessionInfo self, SseSerializer serializer);

  @protected
  void sse_encode_session_state(SessionState self, SseSerializer serializer);

  @protected
  void sse_encode_sync_status(SyncStatus self, SseSerializer serializer);

  @protected
  void sse_encode_thread_event(ThreadEvent self, SseSerializer serializer);

  @protected
  void sse_encode_thread_info(ThreadInfo self, SseSerializer serializer);

  @protected
  void sse_encode_thread_list_diff(
    ThreadListDiff self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thread_summary(ThreadSummary self, SseSerializer serializer);

  @protected
  void sse_encode_timeline_diff(TimelineDiff self, SseSerializer serializer);

  @protected
  void sse_encode_timeline_item(TimelineItem self, SseSerializer serializer);

  @protected
  void sse_encode_timeline_item_kind(
    TimelineItemKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_upload_progress(
    UploadProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatClient(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatThreadList(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatTimeline(
    int ptr,
  );
}
